name: "Alap build teszt"

on: push
jobs:
  Build_Project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JUnit tests
      - run: |
          mvn clean install

