name: "Alap build teszt"

on: push
jobs: 
  IO_Test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          mkdir lib
          cd lib/
          wget https://search.maven.org/remotecontent?filepath=org/json/json/20210307/json-20210307.jar
          cd ..
      - run: javac -cp lib/json-20210307.jar *.java
      - run: |
            for test in `ls tests/*.txt`; do
              java Main < $test > $test.gen
              diff $test.gen $test.out
            done