name: "Alap build teszt"

on: push
jobs: 
  Build_Project:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: javac *.java
  IO_Test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: javac *.java
      - run: |
            for test in `ls tests/*.txt; do
              java Main < $test > $test.gen
              diff $test.gen $test.out
            done